version: '3.8'

services:
  cerebrogpt:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
      - FLASK_ENV=development
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: cerebrogpt-network
