[build]
builder = "nixpacks"

[deploy]
startCommand = "docker-compose up --build"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
NODE_ENV = "production"
FLASK_ENV = "production"
